paths:
  /debat/infodebats:
    get:
      tags:
      - "infoDebat"
      summary: "get debat information for a given enity"
      description: ""
      operationId: "getDebatInfoByEntityId"
      produces:
      - "application/json"
      parameters:
      - name: "entityType"
        in: "path"
        description: "entity name"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
              $ref: "#/definitions/InfoDebatWS"
        400:
          description: "Specific entity for the given id not FOUND"
    
  

  InfoDebat:
    type: "object"
    properties:
      idDebat:
        type: "integer"
        description: "the id of the Debat for the given entity"
      sujet:
        type: "string"
      nombrePost:
        type: "integer"
        
  InfoDebatWS:
    type: "object"
    properties:
      entityId:
        type: "integer"
        description: "The ID of a particular entity"
      entityType:
        type: "string"
        description: "the name of a particular entity"
        example: "PILIER"
        enum:
        - "PILIER"
        - "AXE"
        - "SECTEUR"
        - "PROJET"
      nombreDebat:
        type: "integer"
        description: "the total debat of the given entity"
      nombrePostGlobal:
        type: "integer"
        description: "the total of all the comment relative for the given debat"
      listDebat:
        type: "array"
        items:
          $ref: "#/definitions/InfoDebat"
